on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: kapasrijkubacr.azurecr.io
        username: ${{ secrets.acr_kapasrijkubacr_username }}
        password: ${{ secrets.acr_kapasrijkubacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/node/plain/container/Application" -f  "node/plain/container/Application/Dockerfile" -t kapasrijkubacr.azurecr.io/kptestproj:${{ github.sha }}
        docker push kapasrijkubacr.azurecr.io/kptestproj:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kptestproj_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kptestproj11f5 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kptestproj11f5`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kptestproj11f5
        container-registry-url: kapasrijkubacr.azurecr.io
        container-registry-username: ${{ secrets.acr_kapasrijkubacr_username }}
        container-registry-password: ${{ secrets.acr_kapasrijkubacr_password }}
        secret-name: kptestprojdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: kptestproj11f5
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          kapasrijkubacr.azurecr.io/kptestproj:${{ github.sha }}
        imagepullsecrets: |
          kptestprojdockerauth