# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Issue Dashboard
        # You may pin to the exact commit or the version.
        # uses: ethomson/issue-dashboard@40be07e6acb728fa9bc4758cd17bbee48a322ed6
        uses: ethomson/issue-dashboard@v1.0.2
        with:
          # The configuration for the dashboards.
          config: |
          title: Issue Query Example
          description: |
            An example of several issue queries, both those that are showing
            number widgets with the number of results, and tables that show
            results.

            These issues are querying the libgit2/libgit2 repository.

          output: |
            format: html
            filename: dashboard.html

          sections: |
            - title: 'Open Issues by Type'
              description: 'Queries of issues by type, using their label.'
              widgets:
            - type: 'number'
              title: 'Bug'
              issue_query: 'repo:libgit2/libgit2 is:open is:issue label:bug'
              color: 'red'
            - type: 'number'
              title: 'Feature'
              issue_query: 'repo:libgit2/libgit2 is:open is:issue label:feature'
              color: 'green'
            - type: 'number'
              title: 'Up for Grabs'
              issue_query: 'repo:libgit2/libgit2 is:open is:issue label:"up for grabs"'
              color: 'blue'
            - type: 'number'
              title: 'Easy Fix'
              issue_query: 'repo:libgit2/libgit2 is:open is:issue label:"easy fix"'
              color: 'blue'

            - title: 'Open Issues by Age'
              description: 'Queries of open issues by their creation date.'
              widgets:
            - type: 'graph'
              title: 'Age'
              elements:
              - title: '7 days'
                issue_query: 'repo:libgit2/libgit2 is:open is:issue created:>{{ date("-7 days") }}'
                color: 'green'
              - title: '30 days'
                issue_query: 'repo:libgit2/libgit2 is:open is:issue created:{{ date("-30 days") }}..{{ date("-7 days") }}'
                color: 'blue'
              - title: '90 days'
                issue_query: 'repo:libgit2/libgit2 is:open is:issue created:{{ date("-90 days") }}..{{ date("-30 days") }}'
              - title: '1 year'
                issue_query: 'repo:libgit2/libgit2 is:open is:issue created:{{ date("-1 year") }}..{{ date("-90 days") }}'
              - title: '2 years'
                issue_query: 'repo:libgit2/libgit2 is:open is:issue created:{{ date("-2 years") }}..{{ date("-1 year") }}'
                color: 'red'
              - title: '3 years'
                issue_query: 'repo:libgit2/libgit2 is:open is:issue created:{{ date("-3 years") }}..{{ date("-2 years") }}'
                color: 'red'
              - title: '>3 years'
                issue_query: 'repo:libgit2/libgit2 is:open is:issue created:<{{ date("-365 days") }}'
                color: 'red'

            - title: 'Pull Requests'
              widgets:
            - type: 'number'
              title: 'Changes Requested'
              issue_query: 'repo:libgit2/libgit2 is:open is:pr review:changes_requested'
              color: 'green'
            - type: 'number'
              title: 'Needs Review'
              issue_query: 'repo:libgit2/libgit2 is:open is:pr review:none'
              color: 'red'
            - type: 'table'
              title: 'Pull Requests with Changes Requested'
              issue_query: 'repo:libgit2/libgit2 is:open is:pr review:changes_requested sort:created-asc'
            - type: 'table'
              title: 'Oldest Pull Requests without Review'
              fields:
              - title: 'Issue'
                property: 'number'
              - title: 'Date'
                value: '{{ date(item.created_date) }}'
              - title: 'Title'
                property: 'title'
              issue_query: 'repo:libgit2/libgit2 is:open is:pr review:none sort:created-asc'
              limit: 15

